send reactions
tulir/whatsmeow pull request #394
Opened 2023-05-31 14:25 UTC by Valdenirmezadri

2023-06-01 05:04 UTC, mamur-rezeki commented
Reaction is already part of message protocol, doesn't need specific function to be added.

2023-06-14 17:05 UTC, tulir commented
`RevokeMessage` is already deprecated so others like that will definitely not be added. `BuildReaction` might make sense, especially if combined with a `BuildMessageKey` to share the code with `BuildRevoke`.

2023-06-16 13:52 UTC, wildy283 commented
thx

2023-07-12 16:14 UTC, tulir requested changes

2023-07-12 16:14 UTC, tulir commented on send.go
> +func (cli *Client) ReactionMessage(chat, sender types.JID, id types.MessageID, reaction string) (SendResponse, error) {
This method needs to be removed

2023-07-12 16:14 UTC, tulir commented on send.go
> +		FromMe:    proto.Bool(true),
This method should be exported, and a new `BuildMessageKey` should be added to share the code with `BuildRevoke`

2023-08-03 13:08 UTC, closed without merging