Feature to add and remove label
tulir/whatsmeow pull request #420
Opened 2023-07-12 03:40 UTC by Romerito007

[Feature to add and remove label](https://github.com/Romerito007/whatsmeow/commit/fcd8dca5bcce25d53eeb4519163c657ca35ffaae)

2023-07-12 16:01 UTC, tulir requested changes

2023-07-12 16:01 UTC, tulir commented on .idea/.gitignore
This file shouldn't be added

2023-07-12 16:01 UTC, tulir commented on appstate/encode.go
> +// BuildPushNameSetting builds an app state patch for alter profile name
```suggestion
// BuildPushNameSetting builds an app state patch for changing the user's push name (the name shown to people who don't have you in contacts).
```

2023-07-12 16:01 UTC, tulir commented on appstate/encode.go
> +// BuildChatLabel builds an app state patch for alter chat label
```suggestion
// BuildChatLabel builds an app state patch for modifying a chat label. This is only for business accounts.
```

2023-07-12 16:01 UTC, tulir commented on appstate/encode.go
> +// BuildMessageLabel builds an app state patch for alter message label
```suggestion
// BuildMessageLabel builds an app state patch for modifying a message label. This is only for business accounts.
```

2023-07-12 16:01 UTC, tulir commented on appstate/encode.go
> +func BuildChatLabel(target types.JID, labelId string, labeled bool) PatchInfo {
Initialisms like `ID` must be written in consistent case, not `Id`: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

(also applies to BuildMessageLabel)

2023-08-02 11:58 UTC, closed without merging

2023-09-12 06:07 UTC, dannywynn commented
@Romerito007 why this was closed?

2023-09-12 09:29 UTC, Romerito007 commented
> @Romerito007 why this was closed?

Code works, I closed it because I thought it wouldn't be merged