appstate: add delete for me
tulir/whatsmeow pull request #702
Opened 2024-11-20 16:30 UTC by marcos-travasso

2025-10-10 19:50 UTC, senpai295 commented on appstate/encode.go
> +func newDeleteForMeMutation(targetJID, senderJID string, messageInfo types.MessageInfo, fromMe string, deleteMedia bool) MutationInfo {
No need to change `JID` to string and `fromMe` should be `bool`

2025-10-10 19:56 UTC, senpai295 requested changes
I think this makes more sense.

2025-10-10 19:56 UTC, senpai295 commented on appstate/encode.go
> +func BuildDeleteForMe(messageInfo types.MessageInfo, deleteMedia bool) PatchInfo {
```
func BuildDeleteForMe(messageInfo types.MessageInfo, deleteMedia bool) PatchInfo {
	
	targetJID, senderJID := messageInfo.Chat, messageInfo.Sender
	if messageInfo.Chat.User == messageInfo.Sender.User {
		senderJID = types.EmptyJID 
	}
	return PatchInfo{
		Type: WAPatchRegularHigh,
		Mutations: []MutationInfo{
			newDeleteForMeMutation(targetJID, senderJID, messageInfo, messageInfo.IsFromMe, deleteMedia),
		},
	}
}`

2026-08-05 17:51 UTC, aryanchoudharypro commented
what's the status on this pr?

2026-09-03 22:38 UTC, closed without merging